language: python
python:
  - "2.7"
env:
  - DJANGO_SETTINGS_MODULE=chileayuda.settings.test
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install coveralls
  - python manage.py migrate
# command to run tests
script: ./run_tests.sh
after_success:
  - coveralls
